//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthQ.SSO.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuthQEntities : DbContext
    {
        public AuthQEntities()
            : base("name=AuthQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Login> Logins { get; set; }
        public DbSet<TeamMember> TeamMembers { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<Trust> Trusts { get; set; }
        public DbSet<TrustedDomain> TrustedDomains { get; set; }
    }
}
