//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthQ.SSO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustedDomain
    {
        public long TrustId { get; set; }
        public string Domain { get; set; }
    
        public virtual Trust Trust { get; set; }
    }
}
